-- AlterTable
ALTER TABLE `Admin` ADD COLUMN `role` ENUM('ADMIN', 'CUSTOMER', 'WARLOCK') NOT NULL DEFAULT 'ADMIN';

-- AlterTable
ALTER TABLE `Customer` ADD COLUMN `role` ENUM('ADMIN', 'CUSTOMER', 'WARLOCK') NOT NULL DEFAULT 'CUSTOMER';

-- AlterTable
ALTER TABLE `Warlock` ADD COLUMN `role` ENUM('ADMIN', 'CUSTOMER', 'WARLOCK') NOT NULL DEFAULT 'WARLOCK';
